apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-tls-client
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: simple-tls-client
        spec:
          containers:
          - name: simple-tls-client
            image: srinmantest.azurecr.io/simple-tls-client:v6
            imagePullPolicy: Always
          restartPolicy: OnFailure