apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echo
  name: echosvc
  namespace: workload2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo
status:
  loadBalancer: {}
